fix: Raise a helpful error on a bogus testplan
I found this because I had added a problem to a testplan and running
dvsim on the resulting block didn't work. But it failed silently!

Now, you get a backtrace:

  ...
    File "/home/rjs/work/dvsim/src/dvsim/sim/flow.py", line 324, in _create_objects
      self.testplan = Testplan(
                      ^^^^^^^^^
    File "/home/rjs/work/dvsim/src/dvsim/testplan.py", line 350, in __init__
      self._parse_testplan(filename, tags, repo_top)
    File "/home/rjs/work/dvsim/src/dvsim/testplan.py", line 463, in _parse_testplan
      self.covergroups = self._create_testplan_elements("covergroup", covergroups, set())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/rjs/work/dvsim/src/dvsim/testplan.py", line 284, in _create_testplan_elements
      raise ValueError(err_msg)
  ValueError: Duplicate items with name handshake_complete_cg.

(which also tells me what I did wrong in my OpenTitan patch!)

Signed-off-by: Rupert Swarbrick <rswarbrick@lowrisc.org>